Repository skojphy/switea, pull requests merged in 2021-11, with the labels that each got.

#1 style: Add default style
  package-lock.json
  src/scss/base/_default.scss
  src/scss/base/_index.scss
  src/scss/components/_button.scss
  src/scss/components/_card-list.scss
  src/scss/components/_form.scss
  src/scss/components/_hader.scss
  src/scss/components/_index.scss
  src/scss/components/_navigation.scss
  src/scss/components/_profile.scss
  src/scss/components/_search.scss
  src/scss/index.scss
  src/scss/pages/_home.scss
  src/scss/pages/_index.scss
  src/scss/pages/_list.scss
  src/scss/pages/_map.scss
  src/scss/pages/_mypage.scss
  src/scss/pages/_recruit.scss
  src/scss/pages/_sign.scss
Labels: enhancement

#28 feat: Add template page markup and style
  src/index.js
  src/pages/template.html
  src/scss/components/_common.scss
  src/scss/components/_index.scss
  src/scss/pages/_index.scss
Labels: enhancement, MarkUp, Style

#31 Feature/list markup
  src/images/filter_symbol.png
  src/images/search_symbool.png
  src/pages/list.html
  src/scss/base/_color.scss
  src/scss/base/_default.scss
Labels: enhancement, MarkUp

#35 Custom component 제작 : navigation
  package-lock.json
  package.json
  src/images/home_activate.png
  src/images/home_activate.svg
  src/images/home_deactivate.png
  src/images/home_deactivate.svg
  src/images/list_activate.png
  src/images/list_activate.svg
  src/images/list_deactivate.png
  src/images/list_deactivate.svg
  src/images/map_activate.png
  src/images/map_activate.svg
  src/images/map_deactivate.png
  src/images/map_deactivate.svg
  src/images/mypage_activate.png
  src/images/mypage_activate.svg
  src/images/mypage_deactivate.png
  src/images/mypage_deactivate.svg
  src/images/recruit_activate.png
  src/images/recruit_activate.svg
  src/images/recruit_deactivate.png
  src/images/recruit_deactivate.svg
  src/index.js
  src/js/components/navigation.js
  src/pages/template.html
  webpack.config.js
Labels: enhancement, MarkUp, Style

#37 feat: Add recruit page markup
  src/pages/recruit.html
Labels: enhancement, MarkUp

#36 style: Add style of search input and toggle button
  src/images/search_symbol.png
  src/pages/list.html
  src/scss/components/_button.scss
  src/scss/components/_search.scss
  src/scss/pages/_list.scss
Labels: Style

#41 feat: Add common form & header style
  package-lock.json
  src/images/header_back.png
  src/images/recruit_calendar.png
  src/pages/recruit.html
  src/scss/components/_common.scss
  src/scss/components/_form.scss
Labels: enhancement, Style

#42 style: Style card list component
  package-lock.json
  src/images/profile/user1_profile.png
  src/images/profile/user2_profile.png
  src/pages/list.html
  src/scss/components/_button.scss
  src/scss/components/_card-list.scss
  src/scss/components/_common.scss
  src/scss/pages/_list.scss
Labels: Style

#46 feat: Markup index.html
  src/index.html
Labels: MarkUp

#47 style: modified recruit common style
  src/pages/recruit.html
  src/scss/components/_button.scss
  src/scss/components/_form.scss
  src/scss/pages/_recruit.scss
Labels: Style

#49 style: Style index.html
  src/index.html
  src/scss/components/_card-list.scss
  src/scss/pages/_home.scss
Labels: Style

#50 Add datepicker in recruit page
  package-lock.json
  package.json
  src/js/recruit.js
  src/pages/recruit.html
  src/scss/components/_common.scss
  src/scss/components/_form.scss
  src/scss/pages/_recruit.scss
Labels: enhancement, JavaScript

#51 Finish Signup, Signin feature
  package-lock.json
  package.json
  src/js/sign.js
  src/js/signin.js
  src/js/signup.js
  src/pages/signin.html
  src/pages/signup.html
  src/scss/components/_form.scss
  src/scss/components/_hader.scss
  src/scss/pages/_index.scss
  src/scss/pages/_sign.scss
  src/scss/pages/_signin.scss
  src/scss/pages/_signup.scss
  webpack.config.js
Labels: enhancement, MarkUp, JavaScript

#57 feat: Add view markup
  src/js/view.js
  src/pages/view.html
  webpack.config.js
Labels: enhancement, MarkUp

#58 Add Kakao map on map page
  .eslintrc.json
  package-lock.json
  src/js/components/navigation.js
  src/js/map.js
  src/js/utils/kakaoMap.js
  src/pages/map.html
  src/scss/pages/_map.scss
  src/scss/utils/_mixin.scss
Labels: enhancement, MarkUp, Style, JavaScript

#59 Audit project
  .gitignore
  package-lock.json
  src/pages/map.html
  src/scss/components/_index.scss
Labels: bug, Fix

#61 feat: Markup filter component
  src/images/filter_symbol.png
  src/pages/list.html
Labels: MarkUp

#62 style: Add view page styling
  src/scss/pages/_index.scss
  src/scss/pages/_view.scss
  webpack.config.js
Labels: Style

#63 style: Style filter component
  src/images/filter_symbol_activate.png
  src/images/filter_symbol_deactivate.png
  src/scss/pages/_list.scss
Labels: Style

#65 feat: Implement functionality of toggling filter modal visibility
  src/images/close.png
  src/js/list.js
  src/pages/list.html
  src/scss/pages/_list.scss
Labels: enhancement, JavaScript

#75 feat: Add function for search by keyword
  src/js/utils/kakaoMap.js
Labels: enhancement, JavaScript

#74 feat: Add function for recruit validate
  src/js/recruit.js
  src/pages/recruit.html
  src/scss/components/_button.scss
  src/scss/components/_form.scss
Labels: enhancement, JavaScript

#76 Recruit search modal markup & styling
  src/js/recruit.js
  src/pages/recruit.html
  src/scss/pages/_recruit.scss
Labels: MarkUp, Style

#80 feat: Implement the functionality to update study lists in real time
  src/index.html
  src/js/list.js
  src/pages/list.html
  src/scss/components/_card-list.scss
Labels: enhancement, JavaScript

#81 Add Marker and cluster
  src/images/pinMarker.svg
  src/js/map.js
  src/js/utils/kakaoMap.js
Labels: enhancement, JavaScript

#84 fix: Move filter style to common components style
  src/images/filter_active.png
  src/images/filter_inactive.png
  src/scss/components/_common.scss
  src/scss/pages/_list.scss
Labels: Style, Fix

#87 feat: Add function for search
  src/js/recruit.js
  src/pages/recruit.html
  src/scss/components/_common.scss
  src/scss/pages/_recruit.scss
Labels: enhancement, JavaScript

#90 refactor: Add datepicker module
  src/js/components/datepicker.js
  src/js/recruit.js
Labels: JavaScript

#98 feat: Add tag module
  src/js/utils/tag.js
Labels: documentation, JavaScript

#77 Modify Signup and Signin page
  package.json
  src/images/mypage/article.png
  src/images/mypage/article.svg
  src/images/mypage/bookmark.png
  src/images/mypage/bookmark.svg
  src/images/mypage/cs.png
  src/images/mypage/cs.svg
  src/images/mypage/edit.png
  src/images/mypage/edit.svg
  src/images/mypage/nextButton.png
  src/images/mypage/nextbutton.svg
  src/images/profile/profileImageDefault.svg
  src/images/profile/profileImageUploadButton.svg
  src/js/signin.js
  src/js/signup.js
  src/js/utils/formValidation.js
  src/pages/sign.html
  src/pages/signin.html
  src/pages/signup.html
  src/scss/base/_color.scss
  src/scss/components/_index.scss
  src/scss/components/_swal.scss
  src/scss/pages/_signin.scss
  src/scss/pages/_signup.scss
Labels: enhancement, MarkUp, Style, JavaScript, Fix

#100 feat: Add function for update user info in server
  src/js/recruit.js
  src/pages/recruit.html
  src/scss/pages/_recruit.scss
Labels: enhancement, JavaScript

#102 Feature for cluster and marker
  src/js/components/navigation.js
  src/js/map.js
  src/js/utils/kakaoMap.js
  src/pages/map.html
  src/scss/pages/_map.scss
Labels: enhancement, MarkUp, Style, JavaScript

#110 feat: Implement filtering functionality of study list
  package.json
  src/js/list.js
  src/pages/list.html
  src/scss/pages/_list.scss
Labels: enhancement, JavaScript

#111 Add feature about search location(address)
  src/js/map.js
  src/js/utils/kakaoMap.js
  src/scss/pages/_map.scss
Labels: enhancement, JavaScript

#109 Add mypage and myarticle
  src/js/myarticle.js
  src/js/mypage.js
  src/pages/myarticle.html
  src/pages/mypage.html
  src/scss/pages/_index.scss
  src/scss/pages/_myarticle.scss
  src/scss/pages/_mypage.scss
  webpack.config.js
Labels: enhancement, JavaScript

#107 Add render function for view page
  src/js/view.js
  src/pages/view.html
  src/scss/components/_button.scss
  src/scss/pages/_view.scss
Labels: enhancement, JavaScript

#117 feat: Implement displaying profile image of study card
  src/js/list.js
Labels: enhancement, JavaScript

#118 View link
  src/js/list.js
  src/scss/components/_card-list.scss
Labels: enhancement, JavaScript

#120 chore: Update svg files on nav-bar
  src/images/home_activate.svg
  src/images/home_deactivate.svg
  src/images/list_activate.svg
  src/images/list_deactivate.svg
  src/images/map_activate.svg
  src/images/map_deactivate.svg
  src/images/mypage_activate.svg
  src/images/mypage_deactivate.svg
  src/images/recruit_activate.svg
  src/images/recruit_deactivate.svg
Labels: Style, Fix

#121 Add spinner module
  src/images/spinner_switea.svg
  src/index.html
  src/index.js
  src/js/components/spinner.js
  src/js/map.js
  src/pages/map.html
  src/scss/components/_common.scss
Labels: enhancement, Style, JavaScript

#124 style: fix spinner position, add shadow
  src/scss/components/_common.scss
Labels: Style

#125 feat: Add welcome svg animation on home-page
  src/images/welcome_switea.svg
  src/js/home.js
Labels: Style, JavaScript

#127 Add function for get geo-location
  src/js/map.js
  src/js/utils/geoLocation.js
Labels: enhancement, JavaScript

#126 refactor: recruit and view page
  src/images/recruit_calendar.png
  src/js/recruit.js
  src/js/utils/tag.js
  src/js/view.js
  src/pages/recruit.html
  src/pages/view.html
  src/scss/components/_common.scss
  src/scss/components/_form.scss
  src/scss/components/_swal.scss
  src/scss/pages/_view.scss
Labels: Style, JavaScript

#130 현재 위치 반영 버튼 생성 및 로직 구현
  src/images/geo_location_icon.png
  src/js/map.js
  src/js/utils/kakaoMap.js
  src/pages/map.html
  src/scss/components/_common.scss
  src/scss/pages/_map.scss
Labels: enhancement, MarkUp, Style, JavaScript

#131 Add spiner and Modify form validation logic
  src/js/myarticle.js
  src/js/mypage.js
  src/js/signin.js
  src/js/signup.js
  src/js/utils/formValidation.js
  src/pages/myarticle.html
  src/pages/mypage.html
  src/pages/signin.html
  src/pages/signup.html
  src/scss/pages/_myarticle.scss
  src/scss/pages/_mypage.scss
Labels: enhancement, MarkUp, JavaScript

#132 Add user profile image
  src/js/myarticle.js
  src/js/mypage.js
  src/pages/mypage.html
  src/scss/pages/_myarticle.scss
Labels: enhancement, Fix

#133 feat: Add function for back to the page
  src/js/myarticle.js
  src/js/mypage.js
  src/js/signin.js
  src/js/signup.js
Labels: enhancement, JavaScript

#134 feat: Add spinner to main page
  src/images/here.png
  src/index.html
  src/js/home.js
  src/js/list.js
  src/js/utils/geoLocation.js
  src/pages/list.html
  src/scss/base/_color.scss
  src/scss/components/_card-list.scss
  src/scss/components/_common.scss
  src/scss/pages/_home.scss
  src/scss/pages/_list.scss
Labels: enhancement, JavaScript

#135 fix: Resolve bug about thumbnail not showing issue
  src/js/map.js
Labels: bug

#137 fix: Resolve keyboard issue about Korean composing
  src/js/utils/tag.js
Labels: bug

#138 Modify article render function and Link article view page
  src/js/myarticle.js
Labels: enhancement, JavaScript

#139 fix: Fix bugs and styles
  src/index.html
  src/js/home.js
  src/js/list.js
  src/scss/components/_card-list.scss
  src/scss/pages/_home.scss
Labels: Style, JavaScript, Fix

#140 Feature/build setting
  .gitignore
  package.json
  webpack.config.js
Labels: enhancement

#141 feat: Add spinner to html, because of flickering issue
  src/index.html
  src/index.js
  src/pages/list.html
  src/pages/map.html
  src/pages/myarticle.html
  src/pages/mypage.html
  src/pages/recruit.html
  src/pages/signin.html
  src/pages/signup.html
  src/pages/template.html
  src/pages/view.html
Labels: enhancement

#143 docs: Edit README.md
  README.md
  src/images/WelcomeSwitea.svg
Labels: documentation
